db:
  name: wp-database
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mariadb
    tag: "10.6.4-focal"
    pullPolicy: IfNotPresent
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
    mysql: 3306